#!/bin/bash

source ~/.config/i3lock/i3lockrc

blank=33000000

khl="$(~/.bin/utils/colorctl -o -$delta -h ${rc:0:6})${rc: -2}"
bshl="$(~/.bin/utils/colorctl -o +$delta -h ${rc:0:6})${rc: -2}"

i3lock --blur $blur \
	   --verif-size=16 \
	   --verif-text="..." \
	   --radius $radius \
	   --ring-width $width \
	   --indicator --clock \
	   --time-size=$timesize \
	   --date-size=$datesize \
	   --time-str="%I:%M" \
	   --date-str="%B %d, %Y" \
	   --line-color=$blank \
	   --inside-color=$ic --ring-color=$rc \
	   --date-color=$rc --time-color=$rc \
	   --separator-color=$rc --keyhl-color=${ic#\#} \
	   --bshl-color=${bshl#\#} \
	   --verif-color=$tc --wrong-color=$rc \
	   --ringver-color=${rvc:-$rc} --ringwrong-color=$wc \
	   --insidever-color=$ic --insidewrong-color=$ic \
