"Boot with standard options"  "rw root=UUID=d829c921-e45b-444c-9bd7-c438958f8c54 quiet splash reboot=pci acpi_backlight=native"	
"Boot to single-user mode"    "rw root=UUID=d829c921-e45b-444c-9bd7-c438958f8c54 splash=silent quiet reboot=pci acpi_backlight=native"
"Boot with minimal options"   "rw root=UUID=d829c921-e45b-444c-9bd7-c438958f8c54"
