#!/bin/bash

declare -i ID
ID=$( xinput list | \egrep -Eo 'Touchpad\s*id\=[0-9]{1,2}' | \egrep -Eo '[0-9]{1,2}' )
echo "Device ID: $ID"
declare -i STATE
STATE=$( xinput list-props $ID | \grep 'Device Enabled' | \awk '{print $4}' )

echo "State: $STATE"
if [ $STATE -eq 1 ]
then
    xinput disable $ID
    notify-send -t 5000 \
'   touchpad 
░░▒▒▓▓██▓▓▒▒░░' \
'   disabled'
    # xsetroot -name "Touchpad disabled!"
else
    xinput enable $ID
    notify-send -t 5000 \
'   touchpad 
░░▒▒▓▓██▓▓▒▒░░' \
'   enabled'
    # xsetroot -name "Touchpad enabled!"
fi
