#!/bin/sh

# rm -rf /tmp/locked.png
# rm -rf /tmp/base.png

# If `imagemagick` is not installed, use a blank screen.
# [ -f /usr/bin/convert ] &&
# scrot -m -z /tmp/base.png &&
# pgrep -x dunst && notify-send -i ~/.config/i3/i3lock/lock.png "Locking computer..." &&
# convert /tmp/base.png -blur 0x8 /tmp/locked.png

# Pause music (mocp, mpd and send the pause key to all mpv videos):
mocp -P >/dev/null 2>&1
mpc pause >/dev/null 2>&1
pauseallmpv >/dev/null 2>&1
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop


i3lock -n -i $HOME/.wallpapers/wall_25.jpg \
    --insidecolor=373445ff --ringcolor=ffffffff --line-uses-inside \
    --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000 \
    --insidevercolor=fecf4dff --insidewrongcolor=d23c3dff \
    --ringvercolor=ffffffff --ringwrongcolor=ffffffff --indpos="x+86:y+1003" \
    --radius=15 --veriftext="" --wrongtext=""

# i3lock -e -f -c 000000 -i /tmp/locked.png

# In five seconds, turn off display unless key press in last 4 seconds.
sleep 5 && [ 4000 -lt "$(xssstate -i)" ] &&  pgrep -x i3lock && xset dpms force off
# lock
#

