#!/usr/bin/env bash

choice_by_rofi() {
    choice=$(echo -e "0: Lock\\n1: Suspend\\n2: Hibernate\\n3: Exit i3\\n4: Reboot\\n5: Poweroff" \
        | rofi -i -lines 6 -dmenu -p 'session' \
        | cut -d ':' -f 1)
}

[[ -z "$DISPLAY" ]] && exit 1

choice_by_rofi
sleep 0.5

[[ -z "$choice" ]] && exit 1

case "$choice" in
    0) exec ~/.bin/i3/lockscreen & dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop & ;;
    1) systemctl suspend & ;;
    2) systemctl hibernate & ;;
    3) exec i3-msg exit & dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop & ;;
    4) systemctl reboot & ;;
    5) systemctl poweroff & ;;
esac
