# -----------------------------------------------------
# Keyboard & Touchpad  (tap handled by libinput, not Hyprland)
# -----------------------------------------------------
input {
  # Keyboard
  kb_layout  = us
  kb_variant =
  kb_model   =
  kb_options =
  kb_rules   =
  follow_mouse = 1

  # Key repeat tuning (optional but feels better)
  repeat_rate  = 35
  repeat_delay = 280

  # Pointer acceleration (0 = default)
  sensitivity = 0

  # Touchpad (tap to click already enabled by libinput)
  touchpad {
    natural_scroll         = true
    disable_while_typing   = true
    scroll_factor          = 0.3
  }
}
